import * as stylex from "@stylexjs/stylex";
import { tokens } from "@open-erp/ui/theme/tokens.stylex";

export const styles = stylex.create({
  page: { gap: tokens.space1 },
  inset: { paddingInlineEnd: tokens.space8 },
  workspace: { width: tokens.setupWorkspaceWithGutter, paddingBlockStart: tokens.space8 },
  focused: {
    width: tokens.setupFocusedWidth,
    paddingInlineStart: 0,
    marginInlineStart: tokens.space8,
  },
  focusedEarly: { paddingBlockStart: tokens.space8 },
  crumb: {
    display: "flex",
    alignItems: "center",
    gap: tokens.space1_5,
    color: tokens.captionForeground,
    fontSize: tokens.fontSizeXs,
  },
  crumbButton: {
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "inherit",
    fontSize: "inherit",
    cursor: "pointer",
    ":focus-visible": { outline: tokens.setupControlFocus, outlineOffset: 2 },
  },
  title: { marginBlockStart: tokens.space4 },
  earlyTitle: { marginBlockStart: tokens.space3 },
  subtitle: { color: tokens.mutedForeground },
  secondary: { color: tokens.mutedForeground },
  caption: { color: tokens.captionForeground, fontSize: tokens.fontSizeXs },
  success: { color: tokens.successForeground },
  warning: { color: tokens.warningForeground },
  blocked: { color: tokens.destructive },
  primary: { color: tokens.primary },
  medium: { fontWeight: tokens.fontWeightMedium },
  semibold: { fontWeight: tokens.fontWeightSemibold },
  section: { marginBlockStart: tokens.space4 },
  section20: { marginBlockStart: tokens.space5 },
  section24: { marginBlockStart: tokens.space6 },
  section28: { marginBlockStart: tokens.space7 },
  note: { marginBlockStart: tokens.space3 },
  tableSpace: { marginBlockStart: tokens.space2 },
  stack: { display: "flex", flexDirection: "column" },
  stack4: { display: "flex", flexDirection: "column", gap: tokens.space1 },
  stack8: { display: "flex", flexDirection: "column", gap: tokens.space2 },
  stack12: { display: "flex", flexDirection: "column", gap: tokens.space3 },
  columns: { display: "flex", alignItems: "start", gap: tokens.space10 },
  openingColumns: {
    display: "flex",
    alignItems: "start",
    gap: tokens.space12,
    width: tokens.setupWorkspaceWidth,
  },
  checklist: {
    width: tokens.setupFocusedWidth,
    display: "flex",
    flexDirection: "column",
    gap: tokens.space4,
  },
  checklistRow: { display: "flex", alignItems: "center", height: tokens.setupChecklistRowHeight },
  checklistLabel: { width: tokens.setupColumn150, flexShrink: 0 },
  checklistDetail: {
    width: tokens.setupChecklistDetailWidth,
    color: tokens.mutedForeground,
    flexShrink: 0,
  },
  checklistStatus: { width: tokens.setupColumn160, flexShrink: 0 },
  blockers: {
    width: tokens.setupDetailWidth,
    padding: tokens.space4,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.input,
    borderRadius: tokens.radiusSurface,
    display: "flex",
    flexDirection: "column",
    gap: tokens.space2_5,
  },
  detail: {
    width: tokens.setupSourceDetailWidth,
    padding: tokens.space4,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.input,
    borderRadius: tokens.radiusSurface,
    display: "flex",
    flexDirection: "column",
    gap: tokens.space3,
  },
  plainAction: {
    paddingInline: tokens.space2,
    backgroundColor: "transparent",
    color: tokens.foreground,
    borderWidth: 0,
  },
  actions: { display: "flex", alignItems: "center", gap: tokens.space1_5 },
  actions8: { display: "flex", alignItems: "center", gap: tokens.space2 },
  actions12: { display: "flex", alignItems: "center", gap: tokens.space3 },
  summary: {
    display: "flex",
    width: tokens.setupInnerWidth,
    borderBlockWidth: 1,
    borderBlockStyle: "solid",
    borderBlockColor: tokens.border,
  },
  statistic: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.space1,
    paddingBlock: tokens.space4,
    width: tokens.setupStatisticWidth,
  },
  statisticNumber: {
    fontSize: tokens.fontSizeLg,
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight24Px,
  },
  rule: {
    width: "100%",
    borderBlockStartWidth: 1,
    borderBlockStartStyle: "solid",
    borderBlockStartColor: tokens.border,
  },
  row: {
    display: "flex",
    alignItems: "center",
    borderBlockEndWidth: 1,
    borderBlockEndStyle: "solid",
    borderBlockEndColor: tokens.border,
    paddingBlock: tokens.space1_75,
  },
  name: { width: tokens.setupColumn140, flexShrink: 0 },
  factLabel: { width: tokens.setupColumn200, flexShrink: 0, color: tokens.mutedForeground },
  facts: {
    display: "flex",
    flexDirection: "column",
    width: tokens.setupInnerWidth,
    borderBlockStartWidth: 1,
    borderBlockStartStyle: "solid",
    borderBlockStartColor: tokens.border,
  },
  factRow: {
    display: "flex",
    paddingBlock: tokens.space3,
    borderBlockEndWidth: 1,
    borderBlockEndStyle: "solid",
    borderBlockEndColor: tokens.border,
  },
  headingRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: tokens.setupInnerWidth,
  },
  controls: {
    width: tokens.setupInnerWidth,
    borderBlockStartWidth: 1,
    borderBlockStartStyle: "solid",
    borderBlockStartColor: tokens.border,
  },
  controlRow: {
    display: "flex",
    alignItems: "center",
    gap: tokens.space4,
    minHeight: tokens.setupSourceRowHeight,
    borderBlockEndWidth: 1,
    borderBlockEndStyle: "solid",
    borderBlockEndColor: tokens.border,
  },
  controlTitle: {
    width: tokens.setupControlLabelWidth,
    flexShrink: 0,
    fontWeight: tokens.fontWeightMedium,
  },
  amberRow: { backgroundColor: tokens.warning, paddingInline: tokens.space3 },
  gate: {
    display: "flex",
    alignItems: "center",
    height: tokens.controlHeightLg,
    borderBlockEndWidth: 1,
    borderBlockEndStyle: "solid",
    borderBlockEndColor: tokens.border,
  },
  gateTitle: { width: tokens.setupFocusedWidth, flexShrink: 0 },
  authority: { display: "flex", gap: tokens.space4, width: tokens.setupInnerWidth },
  authorityCard: {
    width: tokens.setupAuthorityWidth,
    padding: tokens.space4,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.input,
    borderRadius: tokens.radiusSurface,
    display: "flex",
    flexDirection: "column",
    gap: tokens.space1,
  },
  banner: {
    width: tokens.setupInnerWidth,
    display: "flex",
    flexDirection: "column",
    gap: tokens.space1,
    padding: tokens.space4,
    backgroundColor: tokens.registerSelected,
    borderRadius: tokens.radiusSurface,
  },
  periodRow: {
    display: "flex",
    alignItems: "center",
    height: tokens.controlHeightIconLg,
    borderBlockEndWidth: 1,
    borderBlockEndStyle: "solid",
    borderBlockEndColor: tokens.border,
  },
  periodLabel: { width: tokens.setupColumn240, flexShrink: 0 },
  select: {
    width: tokens.setupMappingWidth,
    fontSize: tokens.fontSizeControl,
    fontWeight: tokens.fontWeightNormal,
  },
  radio: {
    appearance: "none",
    width: tokens.setupDecisionRadioSize,
    height: tokens.setupDecisionRadioSize,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: tokens.input,
    borderRadius: tokens.radiusSurface,
    margin: 0,
    backgroundColor: tokens.workspaceSurface,
    ":checked": { borderWidth: 5, borderColor: tokens.primary },
    ":focus-visible": { outline: tokens.setupControlFocus, outlineOffset: 2 },
  },
  radioOptions: { display: "flex", gap: tokens.space5 },
  radioOption: { display: "flex", alignItems: "center", gap: tokens.space2 },
  responsibilityGroups: {
    marginBlockStart: tokens.space5,
    display: "flex",
    flexDirection: "column",
    gap: tokens.space4_5,
  },
  dialogHeading: {
    fontSize: tokens.fontSizeSm,
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeight18Px,
  },
  dialogCopy: { display: "flex", flexDirection: "column", gap: tokens.space1_5 },
});

