import * as stylex from "@stylexjs/stylex";

/** Page 00 Kanon in Paper is the source. Change a value there first, then here. */
export const kanon = stylex.defineConsts({
  colorText: "var(--kanon-color-text)",
  colorSecondary: "var(--kanon-color-secondary)",
  colorCaption: "var(--kanon-color-caption)",
  colorAction: "var(--kanon-color-action)",
  colorActionHover: "var(--kanon-color-action-hover)",
  colorSuccess: "var(--kanon-color-success)",
  colorWarning: "var(--kanon-color-warning)",
  colorError: "var(--kanon-color-error)",
  colorMuted: "var(--kanon-color-muted)",
  colorOnAction: "var(--kanon-color-on-action)",
  colorSurface: "var(--kanon-color-surface)",
  colorSideSurface: "var(--kanon-color-side-surface)",
  colorViewer: "var(--kanon-color-viewer)",
  colorRule: "var(--kanon-color-rule)",
  colorControl: "var(--kanon-color-control)",
  colorSelectedRow: "var(--kanon-color-selected-row)",
  colorEvidence: "var(--kanon-color-evidence)",
  colorAvatar: "var(--kanon-color-avatar)",
  colorAvatarClient: "var(--kanon-color-avatar-client)",
  colorScrim: "var(--kanon-color-scrim)",
  colorToast: "var(--kanon-color-toast)",
  colorToastLink: "var(--kanon-color-toast-link)",
  colorUnknownBackground: "var(--kanon-color-unknown-background)",
  colorUnknownBorder: "var(--kanon-color-unknown-border)",
  colorUnknownText: "var(--kanon-color-unknown-text)",
  colorBlockedBackground: "var(--kanon-color-blocked-background)",
  colorBlockedBorder: "var(--kanon-color-blocked-border)",
  colorBlockedText: "var(--kanon-color-blocked-text)",
  colorRiskyBorder: "var(--kanon-color-risky-border)",
  colorChartCost: "var(--kanon-color-chart-cost)",
  colorChartGrid: "var(--kanon-color-chart-grid)",
  colorChartMark: "var(--kanon-color-chart-mark)",

  fontUi: "Inter, system-ui, sans-serif",
  fontCode: "Menlo, ui-monospace, monospace",
  textFigure: "2rem",
  textPage: "1rem",
  textSection: "0.875rem",
  textBody: "0.8125rem",
  textCaption: "0.75rem",
  textMicro: "0.625rem",
  leadingFigure: "2.375rem",
  leadingPage: "1.25rem",
  leadingSection: "1.125rem",
  leadingBody: "1rem",
  leadingReading: "1.25rem",
  weightRegular: "400",
  weightMedium: "500",
  weightSemibold: "600",
  weightBold: "700",
  trackingFigure: "-0.02em",

  spaceHair: "1px",
  space05: "2px",
  space1: "0.25rem",
  space2: "0.5rem",
  space3: "0.75rem",
  space4: "1rem",
  space5: "1.25rem",
  space6: "1.5rem",
  space7: "1.75rem",
  space8: "2rem",

  sizeSidebar: "224px",
  sizePanel: "420px",
  sizeQueue: "216px",
  sizeFocused: "1000px",
  sizeBar: "48px",
  sizeRow: "40px",
  sizeRowTall: "52px",
  sizeCardRow: "38px",
  sizeGroupHeader: "40px",
  sizeStatusColumn: "22px",
  sizeStateColumn: "150px",
  sizeAmountColumn: "100px",
  sizeLabelColumn: "110px",
  sizeCompareLabel: "72px",
  sizeLedgerColumn: "72px",
  sizeButtonPrimary: "36px",
  sizeButton: "32px",
  sizeButtonSmall: "28px",
  sizeIcon: "14px",
  sizeAvatar: "22px",
  sizeSheetWidth: "28px",
  sizeSheetHeight: "34px",
  sizeToast: "400px",
  sizeDialog: "520px",
  sizeDrawer: "400px",
  sizeSelectedEdge: "3px",

  radiusSheet: "3px",
  radiusControl: "6px",
  radiusCard: "8px",
  radiusOverlay: "12px",
  radiusPill: "9999px",

  shadowPrimary: "var(--kanon-shadow-primary)",
  shadowSelected: "var(--kanon-shadow-selected)",
  shadowFocus: "var(--kanon-shadow-focus)",
  shadowOverlay: "var(--kanon-shadow-overlay)",
  shadowToast: "var(--kanon-shadow-toast)",
  shadowDrawer: "var(--kanon-shadow-drawer)",
  shadowDocument: "var(--kanon-shadow-document)",

  durationQuick: "150ms",
  easeOut: "cubic-bezier(0.23, 1, 0.32, 1)",
});
