import type { Locale } from "@/paraglide/runtime";

const en = {
  unrelated: "Unrelated",
  vouchers: "Vouchers",
  dateAndState: "Date and state",
  balanced: "Balanced",
  supplierInvoice: "Supplier invoice",
  linkChanges: "Link changes",
  paymentAllocation: "Payment allocation",
  unchanged: "Unchanged",
  bankMatching: "Bank matching",
  taxAccountMatching: "Tax account matching",
  invoice: "Invoice",
  assetAndDeferralPlans: "Asset and deferral plans",
  reports: "Reports",
  closingBasis: "Closing basis",
  affectedRecord: "Affected record",
  vat: "VAT",
  invoice2: "invoice",
  correctionBundle: "Correction bundle",
  isOutdated: "is outdated",
  correctionBundleFor: "Correction bundle for",
  whatYouApprove: "What you approve",
  bundle: "Bundle",
  digest: "Digest",
  postingDate: "Posting date",
  lockedPeriod: ", locked period",
  openPeriod: ", open period",
  reversal: "Reversal",
  reason: "Reason",
  steps: "STEPS",
  step1Prepared: "1. Prepared",
  step2Approval: "2. Approval",
  shownHere: "Shown here",
  netBalance: "Net balance",
  retained: "retained",
  effectsInOtherRegisters: "EFFECTS IN OTHER REGISTERS",
  same: "Same",
  changed: "Changed",
  retained2: "Retained",
  outstanding: "outstanding",
  paymentAllocations: "Payment allocations",
  basisDigest: "Basis digest",
  dependenciesUsedByTheBundle: "DEPENDENCIES USED BY THE BUNDLE",
  dependency: "Dependency",
  prepared: "Prepared",
  now: "Now",
  status: "Status",
  blocked: "Blocked",
  affected: "Affected",
  posted: "Posted",
  outdated: "Outdated",
  awaitingApproval: "Awaiting approval",
  prepareAgainOnTheCurrentBasis: "Prepare again on the current basis",
  whatChangesAndWhatIsRetained: "What changes and what is retained",
  oneBundleWithThreeVouchers: "One bundle with three vouchers",
  reversalAndReplacementCannotBeApproved:
    "Reversal and replacement cannot be approved or posted separately. Approval covers the bundle digest.",
  step3ReversalAndReplacementPostTogether: "3. Reversal and replacement post together",
  afterApproval: "After approval",
  step4OneReceiptForTheComplete: "4. One receipt for the complete bundle",
  ifEitherPostingFailsNeitherReversal:
    "If either posting fails, neither reversal nor replacement is posted. The original stays unchanged.",
  bundleVouchersDebitsPositiveAndCredits: "BUNDLE VOUCHERS, DEBITS POSITIVE AND CREDITS NEGATIVE",
  netBalanceIncludesTheOriginalReversal:
    "Net balance includes the original, reversal and replacement together. The change from the original is shown separately below.",
  bookkeeping: "Bookkeeping",
  reviewCorrectionBundle: "Review correction bundle",
  approveTheCompleteCorrection: "Approve the complete correction",
  prepareAgainOnTheCurrentBasis2: "Prepare again on the current basis",
  openThePeriodWorkflow: "Open the period workflow",
  reviewTheNewCorrectionBundle: "Review the new correction bundle",
  evidenceImpactsAndCorrectionHistory: "Evidence, impacts and correction history",
};

const sv: typeof en = {
  unrelated: "Inte berörd",
  vouchers: "Verifikat",
  dateAndState: "Datum och läge",
  balanced: "Balanserar",
  supplierInvoice: "Leverantörsfaktura",
  linkChanges: "Länk byts",
  paymentAllocation: "Betalningsfördelning",
  unchanged: "Oförändrad",
  bankMatching: "Bankmatchning",
  taxAccountMatching: "Skattekontomatchning",
  invoice: "Faktura",
  assetAndDeferralPlans: "Tillgångs- och periodiseringsplaner",
  reports: "Rapporter",
  closingBasis: "Stängningsunderlag",
  affectedRecord: "Berörd post",
  vat: "Moms",
  invoice2: "faktura",
  correctionBundle: "Rättelsepaket",
  isOutdated: "är inaktuellt",
  correctionBundleFor: "Rättelsepaket för",
  whatYouApprove: "Det här godkänner du",
  bundle: "Paket",
  digest: "Kontrollsumma",
  postingDate: "Bokförs i",
  lockedPeriod: ", låst period",
  openPeriod: ", öppen period",
  reversal: "Backning",
  reason: "Skäl",
  steps: "STEG",
  step1Prepared: "1. Förberedd",
  step2Approval: "2. Godkännande",
  shownHere: "Visas här",
  netBalance: "Netto",
  retained: "bevaras",
  effectsInOtherRegisters: "EFFEKTER I ÖVRIGA REGISTER",
  same: "Samma",
  changed: "Ändrad",
  retained2: "Bevarat",
  outstanding: "kvar att betala",
  paymentAllocations: "Betalningsfördelningar",
  basisDigest: "Kontrollsumma för underlaget",
  dependenciesUsedByTheBundle: "BEROENDEN SOM PAKETET BYGGDE PÅ",
  dependency: "Beroende",
  prepared: "Förberedd",
  now: "Nu",
  status: "Läge",
  blocked: "Stoppad",
  affected: "Berörd",
  posted: "Bokfört",
  outdated: "Inaktuellt",
  awaitingApproval: "Väntar på godkännande",
  prepareAgainOnTheCurrentBasis: "Förbered om på nuvarande underlag",
  whatChangesAndWhatIsRetained: "Vad som ändras och vad som bevaras",
  oneBundleWithThreeVouchers: "Ett paket med tre verifikat",
  reversalAndReplacementCannotBeApproved:
    "Backning och ersättning kan inte godkännas eller bokföras var för sig. Godkännandet gäller paketets kontrollsumma.",
  step3ReversalAndReplacementPostTogether: "3. Backning och ersättning bokförs i ett steg",
  afterApproval: "Efter godkännande",
  step4OneReceiptForTheComplete: "4. Ett kvitto för hela paketet",
  ifEitherPostingFailsNeitherReversal:
    "Misslyckas något bokförs ingenting, varken backning eller ersättning. Originalet ändras inte.",
  bundleVouchersDebitsPositiveAndCredits:
    "VERIFIKATEN I PAKETET, DEBET MED PLUS OCH KREDIT MED MINUS",
  netBalanceIncludesTheOriginalReversal:
    "Netto visar original, backning och ersättning tillsammans. Förändringen mot originalet visas separat nedan.",
  bookkeeping: "Bokföring",
  reviewCorrectionBundle: "Granska rättelsepaket",
  approveTheCompleteCorrection: "Godkänn hela rättelsen",
  prepareAgainOnTheCurrentBasis2: "Förbered om på nuvarande underlag",
  openThePeriodWorkflow: "Öppna periodens arbetsflöde",
  reviewTheNewCorrectionBundle: "Granska det nya rättelsepaketet",
  evidenceImpactsAndCorrectionHistory: "Underlag, följder och rättelsehistorik",
};

export function bundleWorkspaceCopy(locale: Locale) {
  return locale === "sv" ? sv : en;
}
